version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: janveubowre89158
      POSTGRES_DB: numbers
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python run.py      
      "
    depends_on:
      - db